# Generated by Django 5.0.6 on 2024-06-19 02:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Independientes', '0019_datoscalculos_caja_comprensacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datoscalculos',
            name='ibc',
            field=models.FloatField(default=40, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(40)]),
        ),
        migrations.AlterField(
            model_name='datoscalculos',
            name='riesgos_laborales',
            field=models.CharField(blank=True, choices=[('Ninguna', 'Ninguna'), ('CIA. DE SEGUROS BOLIVAR S.A.\t', 'CIA. DE SEGUROS BOLIVAR S.A.\t'), ('COMPAÑIA DE SEGUROS DE VIDA AURORA\t', 'COMPAÑIA DE SEGUROS DE VIDA AURORA\t'), ('COMPAÑIA SURAMERICANA ADMINISTRADORA DE RIESGOS PROFESIONALES Y SEGUROS VIDA\t', 'COMPAÑIA SURAMERICANA ADMINISTRADORA DE RIESGOS PROFESIONALES Y SEGUROS VIDA\t'), ('LA EQUIDAD SEGUROS DE VIDA ORGANISMO COOPERATIVO – LA EQUIDAD VIDA', 'LA EQUIDAD SEGUROS DE VIDA ORGANISMO COOPERATIVO – LA EQUIDAD VIDA'), ('MAPFRE COLOMBIA VIDA SEGUROS S', 'MAPFRE COLOMBIA VIDA SEGUROS S'), ('POSITIVA COMPAÑIA DE SEGUROS', 'POSITIVA COMPAÑIA DE SEGUROS'), ('RIESGOS PROFESIONALES COLMENA S.A COMPAÑÍA DE SEGUROS DE VIDA', 'RIESGOS PROFESIONALES COLMENA S.A COMPAÑÍA DE SEGUROS DE VIDA'), ('SEGUROS DE VIDA ALFA S.A.', 'SEGUROS DE VIDA ALFA S.A.'), ('SEGUROS DE VIDA COLPATRIA S.A.', 'SEGUROS DE VIDA COLPATRIA S.A.')], default='Ninguna', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='independiente',
            name='riesgos_laborales',
            field=models.CharField(blank=True, choices=[('Ninguna', 'Ninguna'), ('CIA. DE SEGUROS BOLIVAR S.A.\t', 'CIA. DE SEGUROS BOLIVAR S.A.\t'), ('COMPAÑIA DE SEGUROS DE VIDA AURORA\t', 'COMPAÑIA DE SEGUROS DE VIDA AURORA\t'), ('COMPAÑIA SURAMERICANA ADMINISTRADORA DE RIESGOS PROFESIONALES Y SEGUROS VIDA\t', 'COMPAÑIA SURAMERICANA ADMINISTRADORA DE RIESGOS PROFESIONALES Y SEGUROS VIDA\t'), ('LA EQUIDAD SEGUROS DE VIDA ORGANISMO COOPERATIVO – LA EQUIDAD VIDA', 'LA EQUIDAD SEGUROS DE VIDA ORGANISMO COOPERATIVO – LA EQUIDAD VIDA'), ('MAPFRE COLOMBIA VIDA SEGUROS S', 'MAPFRE COLOMBIA VIDA SEGUROS S'), ('POSITIVA COMPAÑIA DE SEGUROS', 'POSITIVA COMPAÑIA DE SEGUROS'), ('RIESGOS PROFESIONALES COLMENA S.A COMPAÑÍA DE SEGUROS DE VIDA', 'RIESGOS PROFESIONALES COLMENA S.A COMPAÑÍA DE SEGUROS DE VIDA'), ('SEGUROS DE VIDA ALFA S.A.', 'SEGUROS DE VIDA ALFA S.A.'), ('SEGUROS DE VIDA COLPATRIA S.A.', 'SEGUROS DE VIDA COLPATRIA S.A.')], default='Ninguna', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='estado_u',
            field=models.BooleanField(default=False),
        ),
    ]
