# Generated by Django 4.2.6 on 2024-06-19 13:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Independientes', '0020_alter_datoscalculos_ibc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datoscalculos',
            name='CCF',
            field=models.CharField(blank=True, choices=[('Ninguna', 'Ninguna'), ('Compensar', 'Compensar'), ('Colsubcidio', 'Colsubcidio'), ('Cafam', 'Cafam'), ('Cofrem', 'Cofrem'), ('Comfacesar', 'Comfacesar')], default='Ninguna', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='datoscalculos',
            name='arl',
            field=models.CharField(blank=True, choices=[('0', 'Ninguno'), ('1', 'Nivel 1'), ('2', 'Nivel 2'), ('3', 'Nivel 3'), ('4', 'Nivel 4'), ('5', 'Nivel 5')], default='0', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='datoscalculos',
            name='salarioBase',
            field=models.FloatField(default=1300000, validators=[django.core.validators.MinValueValidator(1300000)]),
        ),
    ]
