# Generated by Django 5.0.7 on 2024-08-05 19:19

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id_cargo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cargo', models.CharField(max_length=30)),
                ('descripcion_cargo', models.TextField()),
                ('nivel_riesgo', models.CharField(choices=[('1', 'Nivel 1'), ('2', 'Nivel 2'), ('3', 'Nivel 3'), ('4', 'Nivel 4'), ('5', 'Nivel 5')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('codigo_departamento', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_departamento', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('numero_identificacion_e', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('primer_nombre', models.CharField(max_length=30)),
                ('segundo_nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('primer_apellido', models.CharField(max_length=30)),
                ('segundo_apellido', models.CharField(blank=True, max_length=30, null=True)),
                ('estado_civil', models.CharField(choices=[('Soltero', 'Soltero'), ('Casado', 'Casado'), ('Divorciado', 'Divorciado'), ('Viudo', 'Viudo'), ('No indica', 'No indica')], max_length=10)),
                ('tipo_documento', models.CharField(choices=[('Cédula', 'Cédula'), ('Pasaporte', 'Pasaporte'), ('Tarjeta de Identidad', 'Tarjeta de Identidad'), ('Cédula de extranjería', 'Cédula de extranjería')], max_length=25)),
                ('correo', models.EmailField(max_length=100, unique=True)),
                ('celular', models.CharField(max_length=10, unique=True)),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], max_length=10)),
                ('fecha_nacimiento', models.DateField(help_text='Ingrese la fecha de nacimiento (YYYY-MM-DD)')),
                ('fecha_exp_documento', models.DateField()),
                ('direccion', models.CharField(max_length=50)),
                ('numero_cuenta_bancaria', models.CharField(max_length=20)),
                ('banco', models.CharField(max_length=30)),
                ('imagen', models.ImageField(upload_to='photos')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('nit', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('razon_social', models.CharField(max_length=100)),
                ('telefono_entidad', models.CharField(max_length=10)),
                ('correo_entidad', models.EmailField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NivelEstudio',
            fields=[
                ('id_nivel_estudio', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_nivel_estudio', models.CharField(max_length=30)),
                ('estado_estudio', models.CharField(choices=[('Culminado', 'Culminado'), ('Cursando', 'Cursando'), ('Aplazado', 'Aplazado')], max_length=20)),
                ('nivel_academico', models.CharField(choices=[('Primaria', 'Primaria'), ('Secundaria', 'Secundaria'), ('Media', 'Media'), ('Técnico', 'Técnico'), ('Tecnológico', 'Tecnológico'), ('Pregrado', 'Pregrado'), ('Especialización', 'Especialización'), ('Maestría', 'Maestría'), ('Doctorado', 'Doctorado')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TipoNovedad',
            fields=[
                ('id_tipo_novedad', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_tipo_novedad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('codigo_ciudad', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_ciudad', models.CharField(max_length=80)),
                ('codigo_departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empresarial.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id_contrato', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('horas_semanales', models.IntegerField()),
                ('salario_asignado', models.FloatField(validators=[django.core.validators.MinValueValidator(1300000)])),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=10)),
                ('tipo_contrato', models.CharField(choices=[('Termino Fijo', 'Termino Fijo'), ('Indefinido', 'Indefinido')], max_length=20)),
                ('id_cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empresarial.cargo')),
                ('numero_identificacion_e', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empresarial.empleado')),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='nit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Empresarial.empresa'),
        ),
        migrations.CreateModel(
            name='HorasExtrasRecargos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField()),
                ('HorasExDiu', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(48), django.core.validators.MinValueValidator(0)])),
                ('HorasExNoc', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(48), django.core.validators.MinValueValidator(0)])),
                ('HorasExFestivaDiu', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(48), django.core.validators.MinValueValidator(0)])),
                ('HorasExFestivaNoc', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(48), django.core.validators.MinValueValidator(0)])),
                ('recargoDiuFes', models.IntegerField(blank=True, null=True)),
                ('recargoNoc', models.IntegerField(blank=True, null=True)),
                ('recargoNocFest', models.IntegerField(blank=True, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empresarial.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id_liquidacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('fecha_calculo', models.DateField(null=True)),
                ('salud_empleado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pension_empleado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salud_empresa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pension_empresa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('arl', models.DecimalField(decimal_places=2, max_digits=10)),
                ('caja_compensacion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vacaciones', models.IntegerField(null=True)),
                ('cesantias', models.IntegerField(null=True)),
                ('intereses_cesantias', models.IntegerField(null=True)),
                ('total_antes_deducciones', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numero_identificacion_e', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empresarial.empleado')),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='id_nivel_estudio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empresarial.nivelestudio'),
        ),
        migrations.CreateModel(
            name='NivelGrado',
            fields=[
                ('id_nivel_grado', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_nivel_grado', models.CharField(choices=[('Grado', 'Grado'), ('Nivel', 'Nivel'), ('No aplica', 'No aplica')], max_length=10)),
                ('salario_minimo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salario_maximo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_meses_expe', models.IntegerField()),
                ('id_nivel_estudio_requerido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empresarial.nivelestudio')),
            ],
        ),
        migrations.AddField(
            model_name='cargo',
            name='id_nivel_grado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empresarial.nivelgrado'),
        ),
        migrations.CreateModel(
            name='PasswordResetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(null=True)),
                ('used', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empresarial.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id_sede', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_sede', models.CharField(max_length=100)),
                ('direccion_sede', models.CharField(max_length=255)),
                ('codigo_ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empresarial.ciudad')),
                ('nit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empresarial.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Novedades',
            fields=[
                ('id_novedad', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_novedad', models.DateField()),
                ('descripcion_novedad', models.TextField()),
                ('numero_identificacion_e', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empresarial.empleado')),
                ('id_tipo_novedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empresarial.tiponovedad')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intentos', models.IntegerField(default=0)),
                ('estado_u', models.BooleanField(default=False)),
                ('contrasena', models.CharField(max_length=88)),
                ('id_rol', models.CharField(choices=[('Admin', 'Admin'), ('Contador', 'Contador'), ('Auxiliar Contable', 'Auxiliar Contable'), ('RRHH', 'RRHH'), ('Empleado General', 'Empleado General')], max_length=30)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empresarial.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='vacacionesCesantias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacaciones_acumulado', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('cesantias_acumuladas', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('intereses_cesantias', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('antiguedad', models.IntegerField(null=True)),
                ('dias_vacaciones', models.IntegerField(null=True)),
                ('numero_identificacion_e', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empresarial.empleado')),
            ],
        ),
    ]
