# Generated by Django 4.2.7 on 2024-08-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresarial', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='imagen',
            new_name='imagen_empleado',
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='id_rol',
            new_name='rol',
        ),
        migrations.AddField(
            model_name='empresa',
            name='imagen_empresa',
            field=models.ImageField(default='', upload_to='photos'),
            preserve_default=False,
        ),
    ]
