# Generated by Django 5.0.6 on 2024-09-15 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresarial', '0002_alter_porcentajeslegales_caja_compensacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porcentajeslegales',
            name='auxilio_transporte',
            field=models.DecimalField(decimal_places=2, help_text='Monto del auxilio de transporte', max_digits=10),
        ),
        migrations.AlterField(
            model_name='porcentajeslegales',
            name='caja_compensacion',
            field=models.DecimalField(decimal_places=2, help_text='Porcentaje de contribución a la caja de compensación', max_digits=5),
        ),
        migrations.AlterField(
            model_name='porcentajeslegales',
            name='cesantias',
            field=models.IntegerField(help_text='Periodo de cálculo de cesantías 360 días 1 enero a 31 de diciembre'),
        ),
        migrations.AlterField(
            model_name='porcentajeslegales',
            name='icbf',
            field=models.DecimalField(decimal_places=2, help_text='Porcentaje de contribución al ICBF', max_digits=5),
        ),
        migrations.AlterField(
            model_name='porcentajeslegales',
            name='intereses_cesantias',
            field=models.DecimalField(decimal_places=2, help_text='Porcentaje de intereses sobre cesantías', max_digits=5),
        ),
        migrations.AlterField(
            model_name='porcentajeslegales',
            name='pension_empleado',
            field=models.DecimalField(decimal_places=2, help_text='Porcentaje de pensión a cargo del empleado', max_digits=5),
        ),
        migrations.AlterField(
            model_name='porcentajeslegales',
            name='pension_empresa',
            field=models.DecimalField(decimal_places=2, help_text='Porcentaje de pensión a cargo de la empresa', max_digits=5),
        ),
        migrations.AlterField(
            model_name='porcentajeslegales',
            name='salud_empleado',
            field=models.DecimalField(decimal_places=2, help_text='Porcentaje de salud a cargo del empleado ejemplo: 4 % ingrese 0.04', max_digits=5),
        ),
        migrations.AlterField(
            model_name='porcentajeslegales',
            name='salud_empresa',
            field=models.DecimalField(decimal_places=2, help_text='Porcentaje de salud a cargo de la empresa', max_digits=5),
        ),
        migrations.AlterField(
            model_name='porcentajeslegales',
            name='sena',
            field=models.DecimalField(decimal_places=2, help_text='Porcentaje de contribución al SENA', max_digits=5),
        ),
        migrations.AlterField(
            model_name='porcentajeslegales',
            name='vacaciones',
            field=models.IntegerField(help_text='Días hábiles de vacaciones'),
        ),
    ]
