# Generated by Django 5.0.6 on 2024-09-16 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresarial', '0004_alter_porcentajeslegales_caja_compensacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nivelgrado',
            name='digitiNivelGrado',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
